services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KONG_PROXY_PORT=${KONG_PROXY_PORT}
        - KONG_ADMIN_PORT=${KONG_ADMIN_PORT}
    container_name: kong
    restart: unless-stopped
    ports:
      - "${KONG_PROXY_PORT}:${KONG_PROXY_PORT}"
      - "${KONG_ADMIN_PORT}:${KONG_ADMIN_PORT}"
    environment:
      KONG_DATABASE: off
      KONG_PROXY_LISTEN: "${KONG_PROXY_HOST}:${KONG_PROXY_PORT}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_HOST}:${KONG_ADMIN_PORT}"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./config/kong.yml:/etc/kong/kong.yml
    networks:
      - services_network

networks:
  services_network:
    name: services_network
    driver: bridge

volumes:
  kong-db-data: