FROM mockoon/cli:latest

WORKDIR /app

COPY environment.json /data/environment.json

ARG WATER_PROVIDER_PORT
ENV WATER_PROVIDER_PORT=${WATER_PROVIDER_PORT}

EXPOSE ${WATER_PROVIDER_PORT}

# Use ENTRYPOINT to fix the base command, and CMD to provide default arguments
ENTRYPOINT ["/bin/sh", "-c"]
CMD exec mockoon-cli start --data /data/environment.json --port "$WATER_PROVIDER_PORT" --type mockoon
