basePath: /api/v1/
definitions:
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.GetProviderByIDResponse:
    properties:
      provider:
        $ref: '#/definitions/response.ProviderResponse'
    type: object
  response.GetProviderByNameResponse:
    properties:
      provider:
        $ref: '#/definitions/response.ProviderResponse'
    type: object
  response.GetProvidersResponse:
    properties:
      providers:
        items:
          $ref: '#/definitions/response.ProviderResponse'
        type: array
    type: object
  response.ProviderResponse:
    properties:
      api_url:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is the API for Bill Aggregation System.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Bill Aggregation System API
  version: "1.0"
paths:
  /providers:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all available providers.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProvidersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get all providers
      tags:
      - Providers
  /providers/{provider_id}:
    get:
      consumes:
      - application/json
      description: Fetches provider details using the provider ID.
      parameters:
      - description: Provider ID
        in: path
        name: provider_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProviderByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get a provider by ID
      tags:
      - Providers
  /providers/name/{provider_name}:
    get:
      consumes:
      - application/json
      description: Fetches provider details using the provider name.
      parameters:
      - description: Provider Name
        in: path
        name: provider_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetProviderByNameResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get a provider by name
      tags:
      - Providers
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
