FROM mockoon/cli:latest

WORKDIR /app

COPY environment.json /data/environment.json

ARG PROVIDER_PORT=5003
ENV PROVIDER_PORT=${PROVIDER_PORT}

EXPOSE ${PROVIDER_PORT}

CMD ["start", "--data", "/data/environment.json", "--port", "5003"]
