services:
  provider-service:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
    container_name: provider-service
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
    command: ["go", "run", "./cmd/http/main.go"]
    depends_on:
      - postgres
    networks:
      - services_network
      - provider_db_network

  postgres:
    image: postgres:14-alpine
    container_name: provider-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - provider-db-data:/var/lib/postgresql/data
    networks:
      - provider_db_network

networks:
  services_network:
    name: services_network
    driver: bridge
  provider_db_network:
    name: provider_db_network
    driver: bridge

volumes:
  provider-db-data: